services:
  serve:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - mkdocs
      - serve
      - --dev-addr
      - 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/workspaces/swiss-ai-center

  format:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - mdwrap
      - --fmt
      - .
    volumes:
      - .:/workspaces/swiss-ai-center
