repo_url: https://github.com/swiss-ai-center/documentation
repo_name: swiss-ai-center/documentation
site_name: Swiss AI Center
site_author: Swiss AI Center contributors
site_url: https://docs.swiss-ai-center.ch
site_description: >-
  Documentation website for the Swiss AI Center project.
copyright: Copyright &copy; 2022 - 2024 Swiss AI Center
nav:
  - Home:
      - index.md
      - Tutorials: tutorials/index.md
      - How-to guides: how-to-guides/index.md
      - Reference: reference/index.md
      - Explanations: explanations/index.md
  - Tutorials:
      - tutorials/index.md
      - Getting started: tutorials/getting-started.md
      - Start the core engine: tutorials/start-the-core-engine.md
      - Create a service to rotate an image (generic template): tutorials/create-a-service-to-rotate-an-image.md
      - Create a service to summarize a text using an existing model (generic template): tutorials/create-a-service-to-summarize-a-text-using-an-existing-model.md
      - Create a service to detect anomalies using a model built from scratch (model from scratch template): tutorials/create-a-service-to-detect-anomalies-using-a-model-built-from-scratch.md
      - Create a pipeline that blurs faces in an image: tutorials/create-a-pipeline-that-blurs-faces-in-an-image.md
  - How-to guides:
      - how-to-guides/index.md
      - How to create a new service: how-to-guides/how-to-create-a-new-service.md
      - How to build, publish and deploy a service: how-to-guides/how-to-build-publish-and-deploy-a-service.md
      - How to update the documentation: how-to-guides/how-to-update-the-documentation.md
      - How to configure a new GitHub repository: how-to-guides/how-to-configure-a-new-github-repository.md
      - How to add DVC to a service: how-to-guides/how-to-add-dvc-to-a-service.md
      - How to deploy the Core engine on an Exoscale Kuburnetes cluster: how-to-guides/how-to-deploy-the-core-engine-on-an-exoscale-kubernetes-cluster.md
  - Reference:
      - reference/index.md
      - Core concepts:
          - Authentication: reference/core-concepts/auth.md
          - Pipeline: reference/core-concepts/pipeline.md
          - Service: reference/core-concepts/service.md
      - Services:
          - ae-ano-detection service: reference/services/ae-ano-detection.md
          - average-shade service: reference/services/average-shade.md
          - classification-benchmark service: reference/services/classification-benchmark.md
          - digit-recognition service: reference/services/digit-recognition.md
          - document-vectorizer service: reference/services/document-vectorizer.md
          - doodle service: reference/services/doodle.md
          - face-analyzer service: reference/services/face-analyzer.md
          - face-detection service: reference/services/face-detection.md
          - gradcam service: reference/services/gradcam.md
          - hugging-face-image-to-text service: reference/services/hugging-face-image-to-text.md
          - hugging-face-text-to-audio service: reference/services/hugging-face-text-to-audio.md
          - hugging-face-text-to-image service: reference/services/hugging-face-text-to-image.md
          - hugging-face-text-to-text service: reference/services/hugging-face-text-to-text.md
          - hugging-face service: reference/services/hugging-face.md
          - image-analyzer service: reference/services/image-analyzer.md
          - image-blur service: reference/services/image-blur.md
          - image-convert service: reference/services/image-convert.md
          - image-crop service: reference/services/image-crop.md
          - image-greyscale service: reference/services/image-greyscale.md
          - image-nsfw-detector service: reference/services/image-nsfw-detector.md
          - image-resize service: reference/services/image-resize.md
          - image-rotate service: reference/services/image-rotate.md
          - image-sam service: reference/services/image-sam.md
          - integrity-checker service: reference/services/integrity-checker.md
          - nlp-langid service: reference/services/nlp-langid.md
          - regression-benchmark service: reference/services/regression-benchmark.md
          - text-summarizer service: reference/services/text-summarizer.md
          - yolov8 service: reference/services/yolov8.md
          - ydata-profiling service: reference/services/ydata-profiling.md
      - Common code: reference/common-code.md
      - Core engine: reference/core-engine.md
      - mdwrap: reference/mdwrap.md
      - chatbot-ollama: reference/chatbot-ollama.md
      - Team: reference/team.md
  - Explanations:
      - explanations/index.md
      - About this documentation: explanations/about-this-documentation.md
      - About Docker and Docker Compose: explanations/about-docker-and-docker-compose.md
      - About Domain-Driven design (DDD): explanations/about-domain-driven-design.md
      - About dotenv support: explanations/about-dotenv-support.md
      - About DVC: explanations/about-dvc.md
      - About envsubst: explanations/about-envsubst.md
      - About Exoscale: explanations/about-exoscale.md
      - About FastAPI: explanations/about-fastapi.md
      - About flake8: explanations/about-flake8.md
      - About GitHub: explanations/about-github.md
      - About GitHub Actions: explanations/about-github-actions.md
      - About GitHub Secrets: explanations/about-github-secrets.md
      - About GlitchTip: explanations/about-glitchtip.md
      - About HEIA-FR: explanations/about-heia-fr.md
      - About kubectl: explanations/about-kubectl.md
      - About Kubernetes: explanations/about-kubernetes.md
      - About Material for MkDocs: explanations/about-material-for-mkdocs.md
      - About minikube: explanations/about-minikube.md
      - About MinIO: explanations/about-minio.md
      - About PostgreSQL: explanations/about-postgresql.md
      - About Pydantic: explanations/about-pydantic.md
      - About pytest: explanations/about-pytest.md
      - About Python: explanations/about-python.md
      - About Python pitfalls: explanations/about-python-pitfalls.md
      - About SQLAlchemy: explanations/about-sqlalchemy.md
      - About SQLModel: explanations/about-sqlmodel.md
      - About SQLite: explanations/about-sqlite.md
      - About yq: explanations/about-yq.md
edit_uri: blob/main/docs/
theme:
  language: en
  custom_dir: docs
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - search
  - social
  - tags
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      fallback_to_build_date: true
  - glightbox
  - minify:
      minify_html: true
extra:
  social:
    - icon: material/earth
      link: https://swiss-ai-center.ch
      name: Swiss AI Center
    - icon: material/github
      link: https://github.com/swiss-ai-center/
      name: Swiss AI Center on GitHub
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js
